CREATE TABLE IF NOT EXISTS Project(
    projectId integer primary key,
    title text,
    projectType text
);

CREATE TABLE IF NOT EXISTS Image(
    imageId integer primary key,
    projectId integer references Project(projectId),
    imageOrder integer,
    description text
);

INSERT INTO Project VALUES(1, 'LESLIE TYNIK CONSULTING - BRANDING', 'GRAPHIC  identity for Leslie Tynik, founder of LTC in NYC');
INSERT INTO Project VALUES(2, 'GRACE HARTNETT WEBSITE', 'Website for the NYC director and set designer');

INSERT INTO Project VALUES(3, 'GRAPHIC DESIGN AS A SUBJECT, A METHOD AND A PRACTICE - A RESOURCE BOOK ON GRAPHIC DESIGN', NULL);
INSERT INTO Project VALUES(4, 'SINAL – 100 Anos de Design das Telecomunicações e dos Correios em Portugal - catalogue', NULL);

INSERT INTO Project VALUES(5, 'A PROJECT ON SURVEILLANCE - PROTECTION, PRIVACY AND FEAR WHAT DO YOU DO, WHEN YOU ARE NOT BEING WATCHED?',NULL);
INSERT INTO Project VALUES(6, 'ALTERNATIVE SOCIETY - WE ESCAPED', 'A BOOK BY CATARINA FREITAS');

INSERT INTO Project VALUES(7, 'CATCHER IN THE RYE + THE REVOLUTION OF EVERYDAY LIFE', 'BOOK REDESIGN');
INSERT INTO Project VALUES(8, 'THE PALACE OF DREAMS', 'PUBLICATION BY CATARINA FREITAS');

INSERT INTO Project VALUES(9,'751 DIAS – O TEMPO NÃO CONSOME A ETERNIDADE', 'DEVELOPED IN ESAD—IDEA WITH INÊS NEPOMUCENO');
INSERT INTO Project VALUES(10,'PRINTING TECHNIQUES','SCREEN PRINTING/ RISOGRAPHY/ LETTERPRESS');

INSERT INTO Project VALUES(11,"FOR THE FUTURE WE PRESENT: 'THOUGHT, ACTION, CONDUCT' THE PROJECT OF A TOTAL LIFE",NULL);
INSERT INTO Project VALUES(12,"THERE'S A SECRET PARADE IN OUR HOMETOWN HERE´S WHAT OUR MOTHERS DON'T SHARE",NULL);

INSERT INTO Project VALUES(13,'COMPLETE LOVE','PHOTOGRAPHY ANALOG SERIES');
INSERT INTO Project VALUES(14,'ESAD — ESCOLA SUPERIOR DE ARTES E DESIGN , MATOSINHOS','WORK DEVELOPED IN ESAD-IDEA.');

INSERT INTO Project VALUES(15,"'REPEAT AFTER ME: WE DO NOT LIVE IN A BUBBLE. WHAT WE DO MATTERS. STAY HOME' - SERIES OF POSTERS",NULL);
INSERT INTO Project VALUES(16,"POSTER 'REPEAT AFTER ME: BEING BLACK ISN'T A CRIME. END POLICE BRUTALITY. BLACK LIVES MATTER'.",NULL);

INSERT INTO Image VALUES(1,1,1,'Leslie Tynik');
INSERT INTO Image VALUES(NULL,1,2,'Leslie Tynik');
INSERT INTO Image VALUES(NULL,1,3,'Leslie Tynik');
INSERT INTO Image VALUES(NULL,1,4,'Leslie Tynik');
INSERT INTO Image VALUES(NULL,1,5,'Leslie Tynik');
INSERT INTO Image VALUES(NULL,1,6,'Leslie Tynik');

INSERT INTO Image VALUES(NULL,2,1,'GRACE HARTNETT WEBSITE');
INSERT INTO Image VALUES(NULL,2,2,'GRACE HARTNETT WEBSITE');
INSERT INTO Image VALUES(NULL,2,3,'GRACE HARTNETT WEBSITE');
INSERT INTO Image VALUES(NULL,2,4,'GRACE HARTNETT WEBSITE');
INSERT INTO Image VALUES(NULL,2,5,'GRACE HARTNETT WEBSITE');
INSERT INTO Image VALUES(NULL,2,6,'GRACE HARTNETT WEBSITE');
INSERT INTO Image VALUES(NULL,2,7,'GRACE HARTNETT WEBSITE');
INSERT INTO Image VALUES(NULL,2,8,'GRACE HARTNETT WEBSITE');

INSERT INTO Image VALUES(NULL,3,1,'A RESOURCE BOOK ON GRAPHIC DESIGN');
INSERT INTO Image VALUES(NULL,3,2,'A RESOURCE BOOK ON GRAPHIC DESIGN');
INSERT INTO Image VALUES(NULL,3,3,'A RESOURCE BOOK ON GRAPHIC DESIGN');

INSERT INTO Image VALUES(NULL,4,1,'SINAL');
INSERT INTO Image VALUES(NULL,4,2,'SINAL');
INSERT INTO Image VALUES(NULL,4,3,'SINAL');

INSERT INTO Image VALUES(NULL,5,1,'A project on surveillance');
INSERT INTO Image VALUES(NULL,5,2,'A project on surveillance');
INSERT INTO Image VALUES(NULL,5,3,'A project on surveillance');

INSERT INTO Image VALUES(NULL,6,1,'Alternative Society');
INSERT INTO Image VALUES(NULL,6,2,'Alternative Society');
INSERT INTO Image VALUES(NULL,6,3,'Alternative Society');

INSERT INTO Image VALUES(NULL,7,1,'Catcher in the rye');
INSERT INTO Image VALUES(NULL,7,2,'Catcher in the rye');
INSERT INTO Image VALUES(NULL,7,3,'Catcher in the rye');

INSERT INTO Image VALUES(NULL,8,1,'The Palace of dreams');
INSERT INTO Image VALUES(NULL,8,2,'The Palace of dreams');
INSERT INTO Image VALUES(NULL,8,3,'The Palace of dreams');

INSERT INTO Image VALUES(NULL,9,1,'751 DIAS – O TEMPO NÃO CONSOME A ETERNIDADE');
INSERT INTO Image VALUES(NULL,9,2,'751 DIAS – O TEMPO NÃO CONSOME A ETERNIDADE');
INSERT INTO Image VALUES(NULL,9,3,'751 DIAS – O TEMPO NÃO CONSOME A ETERNIDADE');

INSERT INTO Image VALUES(NULL,10,1,'PRINTING TECHNIQUES');
INSERT INTO Image VALUES(NULL,10,2,'PRINTING TECHNIQUES');
INSERT INTO Image VALUES(NULL,10,3,'PRINTING TECHNIQUES');

INSERT INTO Image VALUES(NULL,11,1,'THE PROJECT OF A TOTAL LIFE');
INSERT INTO Image VALUES(NULL,11,2,'THE PROJECT OF A TOTAL LIFE');
INSERT INTO Image VALUES(NULL,11,3,'THE PROJECT OF A TOTAL LIFE');

INSERT INTO Image VALUES(NULL, 12,1,'THERE´S A SECRET PARADE IN OUR HOMETOWN HERE´S WHAT OUR MOTHERS DON´T SHARE');
INSERT INTO Image VALUES(NULL, 12,2,'THERE´S A SECRET PARADE IN OUR HOMETOWN HERE´S WHAT OUR MOTHERS DON´T SHARE');
INSERT INTO Image VALUES(NULL, 12,3,'THERE´S A SECRET PARADE IN OUR HOMETOWN HERE´S WHAT OUR MOTHERS DON´T SHARE');

INSERT INTO Image VALUES(NULL,13,1,'COMPLETE LOVE');
INSERT INTO Image VALUES(NULL,13,2,'COMPLETE LOVE');
INSERT INTO Image VALUES(NULL,13,3,'COMPLETE LOVE');

INSERT INTO Image VALUES(NULL,14,1,'ESAD — ESCOLA SUPERIOR DE ARTES E DESIGN');
INSERT INTO Image VALUES(NULL,14,2,'ESAD — ESCOLA SUPERIOR DE ARTES E DESIGN');
INSERT INTO Image VALUES(NULL,14,3,'ESAD — ESCOLA SUPERIOR DE ARTES E DESIGN');

INSERT INTO Image VALUES(NULL,15,1,"WE DO NOT LIVE IN A BUBBLE");
INSERT INTO Image VALUES(NULL,15,2,"WE DO NOT LIVE IN A BUBBLE");
INSERT INTO Image VALUES(NULL,15,3,"WE DO NOT LIVE IN A BUBBLE");

INSERT INTO Image VALUES(NULL,16,1,"BLACK LIVES MATTER");
INSERT INTO Image VALUES(NULL,16,2,"BLACK LIVES MATTER");